version: '3.7'
services:
  database:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: mutillidae
  database_admin:
    depends_on:
    - database
    image: phpmyadmin:latest
    environment:
      MYSQL_ROOT_PASSWORD: mutillidae
    ports:
    - 127.0.0.1:81:80
  www:
    depends_on:
    - database
    - ldap
    build: ./www
    environment:
        - VIRTUAL_HOST=mutillidae.local,cors.mutillidae.local
    volumes:
    # Make the Apache log files on the image available to localhost
    - "./www/var-log-apache2/:/var/log/apache2/"

    ports:
    - 127.0.0.1:80:80
    - 127.0.0.1:443:443
  ldap:
    build: ./ldap
    environment:
      LDAP_ADMIN_PASSWORD: mutillidae
      LDAP_BASE_DN: dc=mutillidae,dc=local
      LDAP_TLS: 'false'
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
  ldap_admin:
    depends_on:
    - ldap
    image: docfactory/phpldapadmin
    ports:
    - 127.0.0.1:82:80
    environment:
      LDAP_NAME: mutillidae.local
      LDAP_HOST: ldap
      LDAP_PORT: 389
      LDAP_DOMAIN: dc=mutillidae,dc=local
volumes:
  ldap_data:
  ldap_config:
